2020-03-06 07:13:24,241 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:13:36,905 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:13:49,454 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:13:57,147 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:14:11,589 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:14:19,925 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:14:26,567 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:35:06,582 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:37:17,584 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:37:20,322 ERROR: Exception on /doctormodelview/list/ [GET] [in c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: doctor.location

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask_appbuilder\security\decorators.py", line 123, in wraps
    return f(self, *args, **kwargs)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask_appbuilder\views.py", line 551, in list
    widgets = self._list()
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask_appbuilder\baseviews.py", line 1118, in _list
    page_size=page_size,
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask_appbuilder\baseviews.py", line 1017, in _get_list_widget
    page_size=page_size,
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\flask_appbuilder\models\sqla\interface.py", line 193, in query
    return count, query.all()
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3233, in all
    return list(self)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\miako\documents\somewheresensible\doctors\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: doctor.location
[SQL: SELECT doctor.id AS doctor_id, doctor.name AS doctor_name, doctor.specialty AS doctor_specialty, doctor.street_address AS doctor_street_address, doctor.location AS doctor_location, doctor."MDL1_class" AS "doctor_MDL1_class", doctor.bio AS doctor_bio, doctor.photo AS doctor_photo, doctor.personal_phone AS doctor_personal_phone, doctor.email AS doctor_email, doctor.publications AS doctor_publications, doctor.notes AS doctor_notes, doctor.work_phone AS doctor_work_phone 
FROM doctor
 LIMIT ? OFFSET ?]
[parameters: (25, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2020-03-06 07:40:50,600 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:41:01,635 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:57:34,298 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 07:58:46,114 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:31:23,319 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:41:15,782 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:42:43,444 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:42:53,395 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:43:06,726 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:43:17,225 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:43:44,109 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:45:55,158 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:46:43,068 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:47:41,046 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:47:50,525 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:48:01,223 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:48:09,670 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:48:17,568 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:49:17,455 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:49:31,145 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:49:37,706 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:49:53,163 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 08:50:01,874 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
2020-03-06 10:33:16,951 INFO: Database startup [in C:\Users\miako\documents\somewheresensible\doctors\project\app\__init__.py:37]
